INSERT INTO ACCOUNT (firstName, lastName ) VALUES ('John', 'Doe')
INSERT INTO ACCOUNT (firstName, lastName ) VALUES ('Jane', 'Doe')
INSERT INTO ACCOUNT (firstName, lastName ) VALUES ('Jim, 'Taylor')
INSERT INTO TRAINEE (programName, exerciseType, reps, intensity) VALUES ('Insanity', 'Cardio', 6, 'beginner')
INSERT INTO TRAINEE (programName, exerciseType, reps, intensity) VALUES ('Prog2', 'Weights', 6, 'beginner')
INSERT INTO TRAINEE (programName, exerciseType, reps, intensity) VALUES ('Prog3', 'Pilates', 6, 'beginner')
INSERT INTO TRAINEE (programName, exerciseType, reps, intensity) VALUES ('Prog4', 'Home workout', 6, 'beginner')
