INSERT INTO ACCOUNT (userName, password, proficiency ) VALUES ('TheGreatWhitJew', 'Qwerty123', 'beginner')
INSERT INTO ACCOUNT (userName, password, proficiency ) VALUES ('TaomanianDevil', 'password', 'intermediate')
INSERT INTO ACCOUNT (userName, password, proficiency ) VALUES ('TheLeet, 'doYouEvenLift', 'expert')
INSERT INTO PROGRAM (programName, exerciseName, reps, sets, programType ) VALUES ('Insanity', 'Mountain climbers', 30, 3, Cardio)
INSERT INTO PROGRAM (programName, exerciseName, reps, sets, programType) VALUES ('Insanity', 'Burpees', 10, 3, Cardio)
INSERT INTO PROGRAM (programName, exerciseName, reps, sets, programType) VALUES ('Yoga 1', 'Downward facing dog', 30, 30, Other)
INSERT INTO PROGRAM (programName, exerciseName, reps, sets, programType) VALUES ('Home Ex', 'Pyramid pushups', 16, 2, HomeWorkouts)