INSERT INTO ACCOUNT (firstName, lastName, proficiency ) VALUES ('John', 'Doe', 'beginner')
INSERT INTO ACCOUNT (firstName, lastName, proficiency ) VALUES ('Jane', 'Doe', 'intermediate')
INSERT INTO ACCOUNT (firstName, lastName, proficiency ) VALUES ('Jim, 'Taylor', 'expert')
INSERT INTO PROGRAM (programName, exerciseName, reps, ) VALUES ('Insanity', 'Cardio', 6)
INSERT INTO PROGRAM (programName, exerciseName, reps, ) VALUES ('Prog2', 'Weights', 6)
INSERT INTO PROGRAM (programName, exerciseName, reps, ) VALUES ('Prog3', 'Pilates', 6)
INSERT INTO PROGRAM (programName, exerciseName, reps, ) VALUES ('Prog4', 'Home workout', 6)